services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phonebook
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phonebook-be-springboot:
    build: ./phonebook-be-springboot
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/phonebook
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  phonebook-fe-react:
    build: ./phonebook-fe-react
    ports:
      - "5173:5173"
    depends_on:
      - phonebook-be-springboot

volumes:
  mysql-data:
